include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    omit_local_variable_types: false
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false
    avoid_function_literals_in_foreach_calls: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_positional_boolean_parameters: false
    type_annotate_public_apis: false
